### ISSUE TITLE
提三点建议

### ISSUE THREAD

**Issue by crper** [yujintang/vscode-stock#2]
- 希望可以增加色彩,红涨绿跌(默认),做成可控选项

![image](https://user-images.githubusercontent.com/8272877/80457759-673be400-8962-11ea-8fd0-fa6638d4234b.png)

- 希望能增加列排序,正序倒序

- 增加市场的色彩标签,效果如下
![image](https://user-images.githubusercontent.com/8272877/80458091-de717800-8962-11ea-97fb-2df274396dc3.png)

这三点都完善的话,这插件就很不错了,谢谢

**Comment by yujintang** [comment]
1.因为现在 vscode 的TreeItem不支持color，所以先用emoji颜色替代
2.排序功能已支持

请升级版本获取，谢谢。
