### ISSUE TITLE
收盘了还在轮询

### ISSUE THREAD

**Issue by landaozhu** [yujintang/vscode-stock#8]
应该是轮询操作吧，就是不断请求接口，但是收盘了还在请求我感觉就有点浪费了。我看到那个蓝色还在刷
![image](https://user-images.githubusercontent.com/41134448/98497478-0a10db80-227f-11eb-8e59-f152210a644d.png)

**Comment by yujintang** [comment]
基本上支持全球的股市， 不仅仅A股时间。
